### ISSUE TITLE
Avaliação

### ISSUE THREAD

**Issue by diegodorgam** [deeplearningunb/emotion#27]
A avaliação é baseada nos 5 seguintes critérios objetivos booleanos: 

1. Proposta
A proposta do projeto é relevante para uma comunidade, em sentido que, a aplicação dessas tecnologias podem trazer algum diferencial positivo para a comunidade que serve.

2. Apresentação
Julga o preparo do arquivo README.md para apresentar o problema, o raciocínio e a solução apresentada pelo projeto, assim como possíveis comparações com outras soluções.

3. Organização
Criação das issues para demonstrar as tarefas, bugs e novas features do projeto, de forma a deixar aberto e claro para a comunidade quais são os desafios do projeto e como ela pode contribuir.

4. Roadmap
Demonstrar por meio de milestones de versões do projeto, como está programada a evolução da solução.

5. Tecnica
Aplicação objetiva dos conhecimentos adquiridos em sala de aula.  

| Proposta | Apresentação | Organização | Roadmap | Técnica |
|:-:|:-:|:-:|:-:|:-:|
| 1 | 1 | 1 | 0 | 0 |
| ok | ok, mas poderia ter um gif animado no readme pra facilitar a visualização | ok | faltou um roadmap ou milestones para elencar os próximos passos | Não encontrei a parte que treina e utiliza a rede neural |

**Comment by lukassxp** [comment]
Foi adicionada ao readme um tópico chamado próximos passos onde foram listadas duas evoluções que o grupo acha que agregariam bastante a aplicação. Cada uma dessas evoluções seria considerada por nós como uma nova release do projeto, tendo em vista que trariam mudanças significativas ao funcionamento do treinamento e no resultado final da classificação.

- [x] @diegodorgam é o suficiente para cumprir o objetivo "4. Roadmap " ?

Caso não seja gostaria de uma indicação do que mais pode ser feito visando completar o objetivo.

**Comment by matheus-rn** [comment]
No projeto, foi utilizado um modelo popular de classificação de imagens, o mobileNet, está disponível como modelo pré-treinado no tensorflow.js, o MobileNet é uma simplificação de redes neurais para possibilitar o seu uso em aplicações web, com isso podemos criar uma aplicação de reconhecimento de images. O nível de precisão de uma MobileNet é menor que as redes neurais tradicionais, para agilizar o tempo de processamento no navegador, mas isso é compensado pela quantidade de amostras que a MobileNet possui na nuvem. Com isso, foi utilizado a aprendizagem por tranferência, que permite combinar novas amostras de imagens personalizadas com o modelo pré-treinado para criar um novo classificador de imagens. Nós utilizamos também o classificador KNN, a razão pela qual precisamos de um classificador é porque, em vez de usar apenas o módulo MobileNet, estamos adicionando amostras personalizadas nunca vistas antes, portanto, o classificador KNN nos permitirá combinar tudo e executar previsões nos dados combinados.

Abaixo estão os trechos do código, do arquivo Home.js:


![home-vue](https://drive.google.com/uc?export=view&id=1mcTNLL7ge52wHPgni-bjKrf4KgBBbDo_)

![home-vue](https://drive.google.com/uc?export=view&id=18aSl7IgpBJJPT-vSjqQdd7G9cXhsX_Av)

**Comment by diegodorgam** [comment]
Atualizado, parabéns!
